name: Create State File
on:
    workflow_dispatch:
env:
    WORKING_DIR: "./state"
jobs:
    create-state-file:
        name: "Creating State File"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3              
            - name: Azure Login
              uses: azure/login@v2
              with:
                creds: ${{secrets.AZURE_CREDENTIALS}}
            - name: Terraform Init
              run: terraform init 
              working-directory: ${{env.WORKING_DIR}}
            - id: plan
              name: Terraform Plan
              working-directory: ${{env.WORKING_DIR}}
              run: terraform plan -no-color
            - id: apply
              name: Terraform Apply
              working-directory: ${{env.WORKING_DIR}}
              run: terraform apply -auto-approve         